// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18444
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SpecFlow.Specs.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("OnLineTaxLoginMobileFeature", Description="Practice Online\r\nMYOB Account - Authorisation\r\nOnLineTaxLoginMobileTablet\r\nOLTLog" +
        "inMT", SourceFile="Features\\OnLineTaxLoginMobileFeature.feature", SourceLine=0)]
    public partial class OnLineTaxLoginMobileFeatureFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "OnLineTaxLoginMobileFeature.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "OnLineTaxLoginMobileFeature", "Practice Online\r\nMYOB Account - Authorisation\r\nOnLineTaxLoginMobileTablet\r\nOLTLog" +
                    "inMT", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void TSuite6146(string mybrowser, string username, string password, string mytitle, string mytitle2, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "TC6146"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("TSuite6146", @__tags);
#line 8
this.ScenarioSetup(scenarioInfo);
#line 9
 testRunner.Given(string.Format("BrowserName {0}", mybrowser), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 10
 testRunner.And(string.Format("Navigate to the OnLineTax  Homepage with title {0}", mytitle), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
 testRunner.When(string.Format("Login with {0}  Password  {1}  page tile  {2}", username, password, mytitle2), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 12
 testRunner.Then(string.Format("Logout   {0}", mytitle), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("TSuite6146, Variant 0", new string[] {
                "TC6146"}, SourceLine=15)]
        public virtual void TSuite6146_Variant0()
        {
            this.TSuite6146("\"android40M\"", "\"ivan@my.com\"", "\"password1\"", "\"MYOB Account - Sign in\"", "\"MYOB Account - Authorisation\"", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("TSuite6146, Variant 1", new string[] {
                "TC6146"}, SourceLine=16)]
        public virtual void TSuite6146_Variant1()
        {
            this.TSuite6146("\"android40M\"", "\"ivan@my.com\"", "\"password1\"", "\"MYOB Account - Sign in\"", "\"MYOB Account - Authorisation\"", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("TSuite6146, Variant 2", new string[] {
                "TC6146"}, SourceLine=17)]
        public virtual void TSuite6146_Variant2()
        {
            this.TSuite6146("\"android40Tablet\"", "\"ivan@my.com\"", "\"password1\"", "\"MYOB Account - Sign in\"", "\"MYOB Account - Authorisation\"", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("TSuite6146, Variant 3", new string[] {
                "TC6146"}, SourceLine=18)]
        public virtual void TSuite6146_Variant3()
        {
            this.TSuite6146("\"android41M\"", "\"ivan@my.com\"", "\"password1\"", "\"MYOB Account - Sign in\"", "\"MYOB Account - Authorisation\"", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("TSuite6146, Variant 4", new string[] {
                "TC6146"}, SourceLine=19)]
        public virtual void TSuite6146_Variant4()
        {
            this.TSuite6146("\"android41M\"", "\"ivan@my.com\"", "\"password1\"", "\"MYOB Account - Sign in\"", "\"MYOB Account - Authorisation\"", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("TSuite6146, Variant 5", new string[] {
                "TC6146"}, SourceLine=20)]
        public virtual void TSuite6146_Variant5()
        {
            this.TSuite6146("\"android41Tablet\"", "\"ivan@my.com\"", "\"password1\"", "\"MYOB Account - Sign in\"", "\"MYOB Account - Authorisation\"", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("TSuite6146, Variant 6", new string[] {
                "TC6146"}, SourceLine=21)]
        public virtual void TSuite6146_Variant6()
        {
            this.TSuite6146("\"android42M\"", "\"ivan@my.com\"", "\"password1\"", "\"MYOB Account - Sign in\"", "\"MYOB Account - Authorisation\"", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("TSuite6146, Variant 7", new string[] {
                "TC6146"}, SourceLine=22)]
        public virtual void TSuite6146_Variant7()
        {
            this.TSuite6146("\"android42M\"", "\"ivan@my.com\"", "\"password1\"", "\"MYOB Account - Sign in\"", "\"MYOB Account - Authorisation\"", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("TSuite6146, Variant 8", new string[] {
                "TC6146"}, SourceLine=23)]
        public virtual void TSuite6146_Variant8()
        {
            this.TSuite6146("\"iPad_61\"", "\"ivan@my.com\"", "\"password1\"", "\"MYOB Account - Sign in\"", "\"MYOB Account - Authorisation\"", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("TSuite6146, Variant 9", new string[] {
                "TC6146"}, SourceLine=24)]
        public virtual void TSuite6146_Variant9()
        {
            this.TSuite6146("\"iPad_70\"", "\"ivan@my.com\"", "\"password1\"", "\"MYOB Account - Sign in\"", "\"MYOB Account - Authorisation\"", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("TSuite6146, Variant 10", new string[] {
                "TC6146"}, SourceLine=25)]
        public virtual void TSuite6146_Variant10()
        {
            this.TSuite6146("\"iPhone61_5\"", "\"ivan@my.com\"", "\"password1\"", "\"MYOB Account - Sign in\"", "\"MYOB Account - Authorisation\"", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("TSuite6146, Variant 11", new string[] {
                "TC6146"}, SourceLine=26)]
        public virtual void TSuite6146_Variant11()
        {
            this.TSuite6146("\"iPhone61_5\"", "\"ivan@my.com\"", "\"password1\"", "\"MYOB Account - Sign in\"", "\"MYOB Account - Authorisation\"", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("TSuite6146, Variant 12", new string[] {
                "TC6146"}, SourceLine=27)]
        public virtual void TSuite6146_Variant12()
        {
            this.TSuite6146("\"iPhone70_5C\"", "\"ivan@my.com\"", "\"password1\"", "\"MYOB Account - Sign in\"", "\"MYOB Account - Authorisation\"", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("TSuite6146, Variant 13", new string[] {
                "TC6146"}, SourceLine=28)]
        public virtual void TSuite6146_Variant13()
        {
            this.TSuite6146("\"iPhone70_5C\"", "\"ivan@my.com\"", "\"password1\"", "\"MYOB Account - Sign in\"", "\"MYOB Account - Authorisation\"", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("TSuite6146, Variant 14", new string[] {
                "TC6146"}, SourceLine=29)]
        public virtual void TSuite6146_Variant14()
        {
            this.TSuite6146("\"iPhone70_5S\"", "\"ivan@my.com\"", "\"password1\"", "\"MYOB Account - Sign in\"", "\"MYOB Account - Authorisation\"", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("TSuite6146, Variant 15", new string[] {
                "TC6146"}, SourceLine=30)]
        public virtual void TSuite6146_Variant15()
        {
            this.TSuite6146("\"iPhone70_5S\"", "\"ivan@my.com\"", "\"password1\"", "\"MYOB Account - Sign in\"", "\"MYOB Account - Authorisation\"", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("OnLineTaxLoginMobileFeature")]
    public partial class OnLineTaxLoginMobileFeatureFeature_NUnit
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "OnLineTaxLoginMobileFeature.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "OnLineTaxLoginMobileFeature", "Practice Online\r\nMYOB Account - Authorisation\r\nOnLineTaxLoginMobileTablet\r\nOLTLog" +
                    "inMT", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("TSuite6146")]
        [NUnit.Framework.CategoryAttribute("TC6146")]
        [NUnit.Framework.TestCaseAttribute("\"android40M\"", "\"ivan@my.com\"", "\"password1\"", "\"MYOB Account - Sign in\"", "\"MYOB Account - Authorisation\"", null)]
        [NUnit.Framework.TestCaseAttribute("\"android40M\"", "\"ivan@my.com\"", "\"password1\"", "\"MYOB Account - Sign in\"", "\"MYOB Account - Authorisation\"", null)]
        [NUnit.Framework.TestCaseAttribute("\"android40Tablet\"", "\"ivan@my.com\"", "\"password1\"", "\"MYOB Account - Sign in\"", "\"MYOB Account - Authorisation\"", null)]
        [NUnit.Framework.TestCaseAttribute("\"android41M\"", "\"ivan@my.com\"", "\"password1\"", "\"MYOB Account - Sign in\"", "\"MYOB Account - Authorisation\"", null)]
        [NUnit.Framework.TestCaseAttribute("\"android41M\"", "\"ivan@my.com\"", "\"password1\"", "\"MYOB Account - Sign in\"", "\"MYOB Account - Authorisation\"", null)]
        [NUnit.Framework.TestCaseAttribute("\"android41Tablet\"", "\"ivan@my.com\"", "\"password1\"", "\"MYOB Account - Sign in\"", "\"MYOB Account - Authorisation\"", null)]
        [NUnit.Framework.TestCaseAttribute("\"android42M\"", "\"ivan@my.com\"", "\"password1\"", "\"MYOB Account - Sign in\"", "\"MYOB Account - Authorisation\"", null)]
        [NUnit.Framework.TestCaseAttribute("\"android42M\"", "\"ivan@my.com\"", "\"password1\"", "\"MYOB Account - Sign in\"", "\"MYOB Account - Authorisation\"", null)]
        [NUnit.Framework.TestCaseAttribute("\"iPad_61\"", "\"ivan@my.com\"", "\"password1\"", "\"MYOB Account - Sign in\"", "\"MYOB Account - Authorisation\"", null)]
        [NUnit.Framework.TestCaseAttribute("\"iPad_70\"", "\"ivan@my.com\"", "\"password1\"", "\"MYOB Account - Sign in\"", "\"MYOB Account - Authorisation\"", null)]
        [NUnit.Framework.TestCaseAttribute("\"iPhone61_5\"", "\"ivan@my.com\"", "\"password1\"", "\"MYOB Account - Sign in\"", "\"MYOB Account - Authorisation\"", null)]
        [NUnit.Framework.TestCaseAttribute("\"iPhone61_5\"", "\"ivan@my.com\"", "\"password1\"", "\"MYOB Account - Sign in\"", "\"MYOB Account - Authorisation\"", null)]
        [NUnit.Framework.TestCaseAttribute("\"iPhone70_5C\"", "\"ivan@my.com\"", "\"password1\"", "\"MYOB Account - Sign in\"", "\"MYOB Account - Authorisation\"", null)]
        [NUnit.Framework.TestCaseAttribute("\"iPhone70_5C\"", "\"ivan@my.com\"", "\"password1\"", "\"MYOB Account - Sign in\"", "\"MYOB Account - Authorisation\"", null)]
        [NUnit.Framework.TestCaseAttribute("\"iPhone70_5S\"", "\"ivan@my.com\"", "\"password1\"", "\"MYOB Account - Sign in\"", "\"MYOB Account - Authorisation\"", null)]
        [NUnit.Framework.TestCaseAttribute("\"iPhone70_5S\"", "\"ivan@my.com\"", "\"password1\"", "\"MYOB Account - Sign in\"", "\"MYOB Account - Authorisation\"", null)]
        public virtual void TSuite6146(string mybrowser, string username, string password, string mytitle, string mytitle2, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "TC6146"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("TSuite6146", @__tags);
#line 8
this.ScenarioSetup(scenarioInfo);
#line 9
 testRunner.Given(string.Format("BrowserName {0}", mybrowser), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 10
 testRunner.And(string.Format("Navigate to the OnLineTax  Homepage with title {0}", mytitle), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
 testRunner.When(string.Format("Login with {0}  Password  {1}  page tile  {2}", username, password, mytitle2), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 12
 testRunner.Then(string.Format("Logout   {0}", mytitle), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
