// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18444
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SpecFlow.Specs.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("FeatureAndroidLogin", SourceFile="Features\\FeatureAndroidLogin.feature", SourceLine=0)]
    public partial class FeatureAndroidLoginFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "FeatureAndroidLogin.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "FeatureAndroidLogin", "", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void TS15462Android(string mybrowser, string username, string password, string mytitle, string mytitle2, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "TC15462"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("TS15462Android", @__tags);
#line 5
this.ScenarioSetup(scenarioInfo);
#line 6
 testRunner.Given(string.Format("BrowserName {0}", mybrowser), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 7
 testRunner.And(string.Format("Navigate to the OnLineTax  Homepage with title {0}", mytitle), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 8
 testRunner.When(string.Format("Login with {0}  Password  {1}  page tile  {2}", username, password, mytitle2), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 9
 testRunner.Then(string.Format("Logout   {0}", mytitle), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("TS15462Android, \"android40M\"", new string[] {
                "TC15462"}, SourceLine=13)]
        public virtual void TS15462Android_Android40M()
        {
            this.TS15462Android("\"android40M\"", "\"ivan@my.com\"", "\"password1\"", "\"MYOB Account - Sign in\"", "\"MYOB Account - Authorisation\"", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("TS15462Android, \"android40Tablet\"", new string[] {
                "TC15462"}, SourceLine=14)]
        public virtual void TS15462Android_Android40Tablet()
        {
            this.TS15462Android("\"android40Tablet\"", "\"ivan@my.com\"", "\"password1\"", "\"MYOB Account - Sign in\"", "\"MYOB Account - Authorisation\"", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("TS15462Android, \"android41M\"", new string[] {
                "TC15462"}, SourceLine=15)]
        public virtual void TS15462Android_Android41M()
        {
            this.TS15462Android("\"android41M\"", "\"ivan@my.com\"", "\"password1\"", "\"MYOB Account - Sign in\"", "\"MYOB Account - Authorisation\"", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("TS15462Android, \"android41Tablet\"", new string[] {
                "TC15462"}, SourceLine=16)]
        public virtual void TS15462Android_Android41Tablet()
        {
            this.TS15462Android("\"android41Tablet\"", "\"ivan@my.com\"", "\"password1\"", "\"MYOB Account - Sign in\"", "\"MYOB Account - Authorisation\"", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("TS15462Android, \"android42M\"", new string[] {
                "TC15462"}, SourceLine=17)]
        public virtual void TS15462Android_Android42M()
        {
            this.TS15462Android("\"android42M\"", "\"ivan@my.com\"", "\"password1\"", "\"MYOB Account - Sign in\"", "\"MYOB Account - Authorisation\"", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("FeatureAndroidLogin")]
    public partial class FeatureAndroidLoginFeature_NUnit
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "FeatureAndroidLogin.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "FeatureAndroidLogin", "", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("TS15462Android")]
        [NUnit.Framework.CategoryAttribute("TC15462")]
        [NUnit.Framework.TestCaseAttribute("\"android40M\"", "\"ivan@my.com\"", "\"password1\"", "\"MYOB Account - Sign in\"", "\"MYOB Account - Authorisation\"", null)]
        [NUnit.Framework.TestCaseAttribute("\"android40Tablet\"", "\"ivan@my.com\"", "\"password1\"", "\"MYOB Account - Sign in\"", "\"MYOB Account - Authorisation\"", null)]
        [NUnit.Framework.TestCaseAttribute("\"android41M\"", "\"ivan@my.com\"", "\"password1\"", "\"MYOB Account - Sign in\"", "\"MYOB Account - Authorisation\"", null)]
        [NUnit.Framework.TestCaseAttribute("\"android41Tablet\"", "\"ivan@my.com\"", "\"password1\"", "\"MYOB Account - Sign in\"", "\"MYOB Account - Authorisation\"", null)]
        [NUnit.Framework.TestCaseAttribute("\"android42M\"", "\"ivan@my.com\"", "\"password1\"", "\"MYOB Account - Sign in\"", "\"MYOB Account - Authorisation\"", null)]
        public virtual void TS15462Android(string mybrowser, string username, string password, string mytitle, string mytitle2, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "TC15462"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("TS15462Android", @__tags);
#line 5
this.ScenarioSetup(scenarioInfo);
#line 6
 testRunner.Given(string.Format("BrowserName {0}", mybrowser), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 7
 testRunner.And(string.Format("Navigate to the OnLineTax  Homepage with title {0}", mytitle), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 8
 testRunner.When(string.Format("Login with {0}  Password  {1}  page tile  {2}", username, password, mytitle2), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 9
 testRunner.Then(string.Format("Logout   {0}", mytitle), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
