// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18444
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SpecFlow.Specs.Features.Template4Reference
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("IEFeature", Description="In order to avoid silly mistakes\r\nAs a math idiot\r\nI want to be told the sum of t" +
        "wo numbers", SourceFile="Features\\Template4Reference\\BrowserIEFeature.feature", SourceLine=0)]
    public partial class IEFeatureFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "BrowserIEFeature.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "IEFeature", "In order to avoid silly mistakes\r\nAs a math idiot\r\nI want to be told the sum of t" +
                    "wo numbers", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void TS901IE(string mybrowser, string googleHome, string myword, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "TC0901IE"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("TS901IE", @__tags);
#line 8
this.ScenarioSetup(scenarioInfo);
#line 9
 testRunner.Given(string.Format("BrowserName {0}", mybrowser), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 10
 testRunner.When(string.Format("Navigate to Google Homepage {0}", googleHome), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 11
 testRunner.And(string.Format("search the word {0}", myword), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 12
 testRunner.Then(string.Format("Assert that page tile include {0}", myword), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("TS901IE, \"IE11os70r08\"", new string[] {
                "TC0901IE"}, SourceLine=16)]
        public virtual void TS901IE_IE11Os70R08()
        {
            this.TS901IE("\"IE11os70r08\"", "\"http://www.google.com.au\"", "\"MYOB IE11\"", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("TS901IE, \"IE10os80r10\"", new string[] {
                "TC0901IE"}, SourceLine=17)]
        public virtual void TS901IE_IE10Os80R10()
        {
            this.TS901IE("\"IE10os80r10\"", "\"http://www.google.com.au\"", "\"Browser IE10\"", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("TS901IE, \"IE10os70r10\"", new string[] {
                "TC0901IE"}, SourceLine=18)]
        public virtual void TS901IE_IE10Os70R10()
        {
            this.TS901IE("\"IE10os70r10\"", "\"http://www.google.com.au\"", "\"Test IE10\"", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("TS901IE, \"IE09os70r11\"", new string[] {
                "TC0901IE"}, SourceLine=19)]
        public virtual void TS901IE_IE09Os70R11()
        {
            this.TS901IE("\"IE09os70r11\"", "\"http://www.google.com.au\"", "\"Test IE09\"", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("TS901IE, \"IE11os81r01\"", new string[] {
                "TC0901IE"}, SourceLine=20)]
        public virtual void TS901IE_IE11Os81R01()
        {
            this.TS901IE("\"IE11os81r01\"", "\"http://www.google.com.au\"", "\"Test 11\"", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("TS901IE, \"IE10os80r08\"", new string[] {
                "TC0901IE"}, SourceLine=21)]
        public virtual void TS901IE_IE10Os80R08()
        {
            this.TS901IE("\"IE10os80r08\"", "\"http://www.google.com.au\"", "\"Test 10\"", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("IEFeature")]
    public partial class IEFeatureFeature_NUnit
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "BrowserIEFeature.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "IEFeature", "In order to avoid silly mistakes\r\nAs a math idiot\r\nI want to be told the sum of t" +
                    "wo numbers", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("TS901IE")]
        [NUnit.Framework.CategoryAttribute("TC0901IE")]
        [NUnit.Framework.TestCaseAttribute("\"IE11os70r08\"", "\"http://www.google.com.au\"", "\"MYOB IE11\"", null)]
        [NUnit.Framework.TestCaseAttribute("\"IE10os80r10\"", "\"http://www.google.com.au\"", "\"Browser IE10\"", null)]
        [NUnit.Framework.TestCaseAttribute("\"IE10os70r10\"", "\"http://www.google.com.au\"", "\"Test IE10\"", null)]
        [NUnit.Framework.TestCaseAttribute("\"IE09os70r11\"", "\"http://www.google.com.au\"", "\"Test IE09\"", null)]
        [NUnit.Framework.TestCaseAttribute("\"IE11os81r01\"", "\"http://www.google.com.au\"", "\"Test 11\"", null)]
        [NUnit.Framework.TestCaseAttribute("\"IE10os80r08\"", "\"http://www.google.com.au\"", "\"Test 10\"", null)]
        public virtual void TS901IE(string mybrowser, string googleHome, string myword, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "TC0901IE"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("TS901IE", @__tags);
#line 8
this.ScenarioSetup(scenarioInfo);
#line 9
 testRunner.Given(string.Format("BrowserName {0}", mybrowser), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 10
 testRunner.When(string.Format("Navigate to Google Homepage {0}", googleHome), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 11
 testRunner.And(string.Format("search the word {0}", myword), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 12
 testRunner.Then(string.Format("Assert that page tile include {0}", myword), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
